INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (1, 'powiekszonymagazynek', 'Extended Clip', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (2, 'kompensator', 'Compensator', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (3, 'MountedScope', 'Scope Pistols MK2', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (4, 'yusuf', 'Gold Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (5, 'celownikdluga', 'Scope Rifles', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (6, 'vipskinmotyl', 'VIP Skin Butterfly', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (7, 'kastetpink', 'Knuckle Skin LOVE', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (8, 'mediumscope', 'Medium Scope', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (9, 'largescope', 'Large Scope', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (10, 'holografik', 'Holographic Sight', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (11, 'platin50', 'Platinium Pistol 50 Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (12, 'woodheavyp', 'Wood Heavy Pistol Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (13, 'wooddlugie', 'Wood Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (14, 'czaszkidlugie', 'Skull Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (15, 'zebradlugie', 'Zebra Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (16, 'boomdlugie', 'Boom Rifles Skin', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (17, 'tactitalmuzle', 'Tactical Muzzle Brake', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (18, 'kastetpimp', 'Knuckle Skin PIMP', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (19, 'kastetbalas', 'Knuckle Skin Ballas', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (20, 'kastetdollar', 'Knuckle Skin Dollar', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (21, 'kastetdiament', 'Knuckle Skin Diamond', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (22, 'kastethate', 'Knuckle Skin Hate', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (23, 'kastetplayer', 'Knuckle Skin Player', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (25, 'kastetvagos', 'Knuckle Skin Vagos', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (26, 'flashlight', 'flashlight Weapons', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (27, 'Suppressor', 'Suppressor', -1, 0, 1);
INSERT INTO `items` (`id`, `name`, `label`, `limit`, `rare`, `can_remove`) VALUES (28, 'grip', 'Grip Rifles', -1, 0, 1);