Config = {}

Config.Animations = {

    --[[{
       name = 'TEST',
        label = 'TEST',
        items = {
		    {label = "Pakowanie do torby", type = "animprop16", data = {lib = "anim@heists@ornate_bank@grab_cash", anim = "grab", car = 0, loop = 1, e = "torba"}},
			{label = "Bed1B - wstawanie", type = "anim", data = {lib = "switch@michael@bedroom", anim = "bed_exit_michael", car = 0, loop = 0, e = ""}},
			{label = "Bed2B", type = "anim", data = {lib = "switch@michael@bedroom", anim = "bed_loop_02_amanda", car = 0, loop = 0, e = ""}},
			{label = "Bed3B", type = "anim", data = {lib = "switch@michael@bedroom", anim = "bed_loop_amanda", car = 0, loop = 0, e = ""}},
			{label = "Bed4B", type = "anim", data = {lib = "switch@michael@bedroom", anim = "bed_loop_michael", car = 0, loop = 0, e = ""}},
			{label = "Bed5B", type = "anim", data = {lib = "switch@michael@bedroom", anim = "bed_react_amanda", car = 0, loop = 0, e = ""}},
			{label = "Bed6B - wstawanie", type = "anim", data = {lib = "switch@michael@bedroom", anim = "get_out_of_bed", car = 0, loop = 0, e = ""}},
			{label = "Bed5C", type = "anim", data = {lib = "switch@michael@bedroom2", anim = "bed_loop_amanda", car = 0, loop = 0, e = ""}},
			{label = "Bed6C", type = "anim", data = {lib = "switch@michael@bedroom2", anim = "bed_loop_michael", car = 0, loop = 0, e = ""}},
			{label = "Bed7C - wstawanie", type = "anim", data = {lib = "switch@michael@bedroom2", anim = "get_out_of_bed", car = 0, loop = 0, e = ""}},
			{label = "Bed8C - wstawanie", type = "anim", data = {lib = "switch@trevor@bed", anim = "bed_getup_1_floyd", car = 0, loop = 0, e = ""}},
			{label = "Bed9C - wstawanie", type = "anim", data = {lib = "switch@trevor@bed", anim = "bed_getup_1_trevor", car = 0, loop = 0, e = ""}},
			{label = "Bed10C - wstawanie", type = "anim", data = {lib = "switch@trevor@bed", anim = "bed_getup_2_floyd", car = 0, loop = 0, e = ""}},
			{label = "Bed11C - wstawanie", type = "anim", data = {lib = "switch@trevor@bed", anim = "bed_getup_2_trevor", car = 0, loop = 0, e = ""}},
			{label = "Bed12C", type = "anim", data = {lib = "switch@trevor@bed", anim = "bed_sleep_floyd", car = 0, loop = 0, e = ""}},
			{label = "Bed13C", type = "anim", data = {lib = "switch@trevor@bed", anim = "bed_sleep_trevor", car = 0, loop = 0, e = ""}},
			{label = "Bed14C?", type = "anim", data = {lib = "switch@trevor@bed", anim = "gc_trv_ig_7_base", car = 0, loop = 0, e = ""}},
			{label = "Bed15C?", type = "anim", data = {lib = "switch@trevor@bed", anim = "gc_trv_ig_7_idle_01", car = 0, loop = 0, e = ""}},
			{label = "Bed16C?", type = "anim", data = {lib = "switch@trevor@bed", anim = "gc_trv_ig_7_idle_02", car = 0, loop = 0, e = ""}},
			{label = "Bed17C?", type = "anim", data = {lib = "switch@trevor@bed", anim = "gc_trv_ig_7_idle_03", car = 0, loop = 0, e = ""}},
			{label = "Bed1D", type = "anim", data = {lib = "timetable@reunited@ig_2", anim = "jimmy_2_bed_endorphins", car = 0, loop = 0, e = ""}},
			{label = "Bed2D", type = "anim", data = {lib = "timetable@reunited@ig_2", anim = "jimmy_base", car = 0, loop = 0, e = ""}},
			{label = "Bed3D", type = "anim", data = {lib = "timetable@reunited@ig_2", anim = "jimmy_getknocked", car = 0, loop = 0, e = ""}},
			{label = "Bed4D", type = "anim", data = {lib = "timetable@reunited@ig_2", anim = "jimmy_masterbation", car = 0, loop = 0, e = ""}},
			{label = "Bed5D", type = "anim", data = {lib = "timetable@reunited@ig_2", anim = "jimmy_rollsflapping", car = 0, loop = 0, e = ""}},
			{label = "Bed1E", type = "anim", data = {lib = "switch@franklin@bed", anim = "sleep_getup_rubeyes", car = 0, loop = 0, e = ""}},
			{label = "Bed2E", type = "anim", data = {lib = "switch@franklin@bed", anim = "sleep_loop", car = 0, loop = 0, e = ""}},
			{label = "Bed3E", type = "anim", data = {lib = "switch@franklin@bed", anim = "stretch_long", car = 0, loop = 0, e = ""}},
			{label = "Bed4E", type = "anim", data = {lib = "switch@franklin@bed", anim = "stretch_short", car = 0, loop = 0, e = ""}},
			{label = "Push1", type = "anim", data = {lib = "ped", anim = "push_l_side", car = 0, loop = 56, e = ""}},
			{label = "Push2", type = "anim", data = {lib = "ped", anim = "push_r_side", car = 0, loop = 56, e = ""}},			
			{label = "PushCar1", type = "anim", data = {lib = "missfam5mcs_6", anim = "push_michael_out_jimmy", car = 0, loop = 0, e = ""}},
			{label = "PushCar2", type = "anim", data = {lib = "missfam5mcs_6", anim = "push_michael_out_player0", car = 0, loop = 0, e = ""}},
     	    {label = "PushCar2", type = "anim", data = {lib = "missfam5mcs_6", anim = "push_michael_out_player0", car = 0, loop = 0, e = ""}},
         	{label = "Victim1", type = "anim", data = {lib = "switch@trevor@bridge", anim = "hold_loop_trevor", car = 0, loop = 51, e = ""}},
         	{label = "Victim2", type = "anim", data = {lib = "switch@trevor@bridge", anim = "hold_loop_victim", car = 0, loop = 1, e = ""}},
         	{label = "Clean1", type = "animprop10", data = {lib = "amb@world_human_maid_clean@", anim = "base", car = 0, loop = 51, e = ""}},
         	{label = "Clean2", type = "animprop10", data = {lib = "amb@world_human_maid_clean@", anim = "idle_d", car = 0, loop = 51, e = ""}},
            {label = "Micro1", type = "anim", data = {lib = "mini@telescope", anim = "enter_front", car = 0, loop = 0, e = ""}},
            {label = "Micro2", type = "anim", data = {lib = "mini@telescope", anim = "exit_front", car = 0, loop = 0, e = ""}},
            {label = "Micro3", type = "anim", data = {lib = "mini@telescope", anim = "idle", car = 0, loop = 0, e = ""}},
            {label = "Micro4", type = "anim", data = {lib = "mini@telescope", anim = "public_enter_front", car = 0, loop = 0, e = ""}},
            {label = "Micro5", type = "anim", data = {lib = "mini@telescope", anim = "public_exit_front", car = 0, loop = 0, e = ""}},
            {label = "Micro6", type = "anim", data = {lib = "mini@telescope", anim = "public_idle", car = 0, loop = 0, e = ""}},
            {label = "Micro7", type = "anim", data = {lib = "mini@telescope", anim = "upright_enter_front", car = 0, loop = 0, e = ""}},
            {label = "Micro8", type = "anim", data = {lib = "mini@telescope", anim = "upright_exit_front", car = 0, loop = 0, e = ""}},
            {label = "Hotwire", type = "anim", data = {lib = "anim@gangops@facility@servers@", anim = "hotwire", car = 1, loop = 50, e = ""}},
            {label = "Tablet", type = "animprop25", data = {lib = "amb@code_human_in_bus_passenger_idles@female@tablet@idle_a", anim = "idle_a", car = 1, loop = 58, e = "tablet"}},     
        }
    },]]
	
    {
        name = 'Wyraz twarzy',
        label = 'Wyraz twarzy',
        items = {
		    {label = "Neutralny", type = "faceexpression", data = {anim = "mood_Normal_1", e = "neutralny"}},
		    {label = "Szczęśliwy", type = "faceexpression", data = {anim = "mood_Happy_1", e = "szczesliwy"}},
		    {label = "Zły", type = "faceexpression", data = {anim = "mood_Angry_1", e = "zly"}},		
		    {label = "Podejrzliwy", type = "faceexpression", data = {anim = "mood_Aiming_1", e = "podejrzliwy"}},
		    {label = "Ból", type = "faceexpression", data = {anim = "mood_Injured_1", e = "bol"}},
		    {label = "Zdenerwowany", type = "faceexpression", data = {anim = "mood_stressed_1", e = "zdenerwowany"}},
		    {label = "Zadowolony", type = "faceexpression", data = {anim = "mood_smug_1", e = "zadowolony"}},
		    {label = "Podpity", type = "faceexpression", data = {anim = "mood_drunk_1", e = "podpity"}},
		    {label = "Zszokowany", type = "faceexpression", data = {anim = "shocked_1", e = "zszokowany"}},
		    {label = "Zamknięte oczy", type = "faceexpression", data = {anim = "mood_sleeping_1", e = "oczy"}},
		    {label = "Przeżuwanie", type = "faceexpression", data = {anim = "eating_1", e = "zucie"}},
        }
    },
	
	{
        name = 'Przywitanie',
        label = 'Przywitanie',
        items = {
            {label = "Siemka [R][P]", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello", car = 1, loop = 56, e = "siema"}},
            {label = "Hej - pomachanie ręką [R]", type = "anim", data = {lib = "missmic4premiere", anim = "wave_a", car = 0, loop = 56, e = "hej"}},
            {label = "Salut 1 - luźny [R]", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@salute", anim = "salute", car = 0, loop = 56, e = "salut"}},
			{label = "Salut 2 - wojskowy [P]", type = "anim", data = {lib = "anim@mp_player_intincarsalutestd@ds@", anim = "enter", car = 1, loop = 2, e = "salut2"}},
        }
    },
	
	{
        name = 'Reakcje',
        label = 'Reakcje',
        items = {
	     	{label = "Facepalm 1 [R][P]", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm", car = 1, loop = 56, e = "facepalm"}},      
	     	{label = "Facepalm 2 [R][P]", type = "anim", data = {lib = "anim@mp_player_intupperface_palm", anim = "enter", car = 1, loop = 50, e = "facepalm2"}},   
	     	{label = "Nie wierze [R][P]", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@face_palm", anim = "face_palm", car = 1, loop = 56, e = "niewierze"}},
			{label = "Złapanie się za głowę [R]", type = "anim", data = {lib = "mini@dartsoutro", anim = "darts_outro_01_guy2", car = 0, loop = 56, e = "zaglowe"}},			
		    {label = "Tak [R][P]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_pleased", car = 1, loop = 57, e = "tak"}},
            {label = "Nie [R][P]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_head_no", car = 1, loop = 57, e = "nie"}},
	     	{label = "Nie ma mowy [R]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_no_way", car = 0, loop = 56, e = "niemamowy"}},
            {label = "Wzruszenie ramionami [R][P]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_shrug_hard", car = 1, loop = 56, e = "wzruszenie"}},
			{label = "Chodź tu [R][P]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_come_here_soft", car = 1, loop = 57, e = "chodz"}},
            {label = "Co? [R][P]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_what_hard", car = 1, loop = 56, e = "co"}},
            {label = "Szlag! [R][P]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_damn", car = 1, loop = 56, e = "szlag"}},
			{label = "Cicho! [R][P]", type = "anim", data = {lib = "anim@mp_player_intuppershush", anim = "idle_a_fp", car = 1, loop = 58, e = "cicho"}},	           
		    {label = "Halo! [R]", type = "anim", data = {lib = "friends@frj@ig_1", anim = "wave_d", car = 0, loop = 56, e = "halo"}},
		    {label = "Tu jestem! [R]", type = "anim", data = {lib = "friends@frj@ig_1", anim = "wave_c", car = 0, loop = 56, e = "tujestem"}},
			{label = "To nie ja", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "taunt_b_player_a", car = 0, loop = 0, e = "tonieja"}},		
            {label = "Przepraszam", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "wow_a_player_b", car = 0, loop = 0, e = "przepraszam"}},		  
		    {label = "Kciuki w górę [R][P]", type = "anim", data = {lib = "anim@mp_player_intincarthumbs_upbodhi@ps@", anim = "enter", car = 1, loop = 58, e = "kciuk"}},
			{label = "Kciuk w dół", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "thumbs_down_a_player_b", car = 0, loop = 0, e = "kciuk2"}},
            {label = "Kciuk jednak w dół", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "thumbs_down_a_player_a", car = 0, loop = 0, e = "kciuk3"}},			   
            {label = "Uspokój się [R]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_easy_now", car = 0, loop = 56, e = "spokojnie"}},   
            {label = "Piąteczka [R]", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "high_five_c_player_b", car = 0, loop = 50, e = "piateczka"}},
            {label = "Brawa 1", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "angry_clap_a_player_a", car = 0, loop = 0, e = "brawa"}},
            {label = "Brawa 2", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "angry_clap_b_player_a", car = 0, loop = 0, e = "brawa2"}},
            {label = "Brawa 3", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "angry_clap_b_player_b", car = 0, loop = 0, e = "brawa3"}},
            {label = "Cieszynka 1 [R]", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "jump_a_player_a", car = 0, loop = 50, e = "cieszynka"}},
            {label = "Cieszynka 2 - skok przez kozła", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "jump_b_player_a", car = 0, loop = 0, e = "cieszynka2"}},
            {label = "Cieszynka 3 - szpagat", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "jump_c_player_a", car = 0, loop = 0, e = "cieszynka3"}},
            {label = "Cieszynka 4 - podskok", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "jump_d_player_a", car = 0, loop = 0, e = "cieszynka4"}},
			{label = "Zwycięzca 1 [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "dance_b_1st", car = 0, loop = 50, e = "zwyciezca"}},
            {label = "Zwycięzca 2 [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "make_noise_a_1st", car = 0, loop = 50, e = "zwyciezca2"}},
            {label = "Udawanie śmierci ", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "pageant_a_player_b", car = 0, loop = 0, e = "udawanie"}},
            {label = "Wślizg na kolanach", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "slide_a_player_a", car = 0, loop = 0, e = "wslizg"}},           
		    {label = "Zamyślenie 1 [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "dance_b_3rd", car = 0, loop = 56, e = "zamyslenie"}},
            {label = "Zamyślenie 2 [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "make_noise_a_2nd", car = 0, loop = 56, e = "zamyslenie2"}},
        }
    },
	
	{
        name = 'Postawa',
        label = 'Postawa',
        items = {
            {label = "Ochroniarz 1", type = "scenario", data = {anim = "WORLD_HUMAN_GUARD_STAND", car = 0, loop = 0, e = "ochroniarz"}},
            {label = "Ochroniarz 2 [R]", type = "anim2", data = {lib = "amb@world_human_stand_guard@male@base", anim = "base", car = 0, loop = 51, e = "ochroniarz2"}},
			{label = "Ochroniarz 3 [R] - zatrzymaj się", type = "animochroniarz", data = {lib = "mini@strip_club@idles@bouncer@stop", anim = "stop", car = 0, loop = 56, e = "ochroniarz3"}},
		    {label = "Policjant 1", type = "scenario", data = {anim = "WORLD_HUMAN_COP_IDLES", car = 0, loop = 1, e = "policjant"}},
			{label = "Policjant 2 [R]", type = "anim", data = {lib = "amb@world_human_cop_idles@male@base", anim = "base", car = 0, loop = 51, e = "policjant2"}},
			{label = "Policjant 3 [R]", type = "anim", data = {lib = "amb@world_human_cop_idles@female@base", anim = "base", car = 0, loop = 51, e = "policjant3"}},
			{label = "Opieranie o barierkę 1 - przód", type = "anim", data = {lib = "amb@prop_human_bum_shopping_cart@male@base", anim = "base", car = 0, loop = 1, e = "opieranie"}},
			{label = "Opieranie o barierkę 2 - z tyłu", type = "anim", data = {lib = "anim@amb@clubhouse@bar@bartender@", anim = "base_bartender", car = 0, loop = 1, e = "opieranie2"}},
			{label = "Opieranie o stół 1 - przód", type = "anim", data = {lib = "anim@amb@clubhouse@bar@drink@base", anim = "idle_a", car = 0, loop = 1, e = "opieranie3"}},
            {label = "Opieranie o stół 2 - przód", type = "anim", data = {lib = "anim@amb@board_room@diagram_blueprints@", anim = "base_amy_skater_01", car = 1, loop = 1, e = "opieranie4"}},
            {label = "Opieranie ściana 1 - nogi na ziemi", type = "anim", data = {lib = "amb@world_human_leaning@male@wall@back@hands_together@base", anim = "base", car = 0, loop = 1, e = "opieranie5"}},
            {label = "Opieranie ściana 2 - noga w górze", type = "anim", data = {lib = "amb@world_human_leaning@male@wall@back@foot_up@base", anim = "base", car = 0, loop = 1, e = "opieranie6"}},
            {label = "Opieranie ściana 3 - nogi na krzyż", type = "anim", data = {lib = "amb@world_human_leaning@male@wall@back@legs_crossed@base", anim = "base", car = 0, loop = 1, e = "opieranie7"}},
            {label = "Siedzienie 1 - na krześle", type = "scenariosit", data = {anim = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER", e = "siedzenie"}},	  
            {label = "Siedzienie 2 - na kanapie", type = "anim", data = {lib = "timetable@ron@ig_3_couch", anim = "base", car = 0, loop = 1, e = "siedzenie2"}},		
		    {label = "Siedzienie 3 - na ziemi", type = "anim", data = {lib = "anim@heists@fleeca_bank@ig_7_jetski_owner", anim = "owner_idle", car = 0, loop = 1, e = "siedzenie3"}},
            {label = "Siedzienie 4 - na menela", type = "scenario", data = {anim = "WORLD_HUMAN_PICNIC", car = 0, loop = 0, e = "siedzenie4"}},
			{label = "Leżenie 1 - na brzuchu", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE", car = 0, loop = 1, e = "lezenie"}},
            {label = "Leżenie 2 - na plecach", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK", car = 0, loop = 0, e = "lezenie2"}},
            {label = "Leżenie 3 - na kanapie", type = "anim", data = {lib = "timetable@ron@ig_3_couch", anim = "laying", car = 0, loop = 1, e = "lezenie3"}},
            {label = "Leżenie 4 - lewy bok", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_left_side@base", anim = "base", car = 0, loop = 1, e = "lezenie4"}},
            {label = "Leżenie 5 - prawy bok", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_right_side@base", anim = "base", car = 0, loop = 1, e = "lezenie5"}},
            {label = "Wypadek 1 - lewy bok", type = "anim", data = {lib = "missheist_jewel", anim = "gassed_npc_customer4", car = 0, loop = 1, e = "wypadek"}},
            {label = "Wypadek 2 - prawy bok", type = "anim", data = {lib = "missheist_jewel", anim = "gassed_npc_guard", car = 0, loop = 1, e = "wypadek2"}},
			{label = "Założone ręce 1 [R][P]", type = "anim", data = {lib = "mini@hookers_sp", anim = "idle_reject_loop_c", car = 1, loop = 57, e = "rece"}},
			{label = "Założone ręce 2 [R][P]", type = "anim", data = {lib = "anim@amb@nightclub@peds@", anim = "rcmme_amanda1_stand_loop_cop", car = 1, loop = 51, e = "rece2"}},
            {label = "Założone ręce 3 [R][P]", type = "anim", data = {lib = "amb@world_human_hang_out_street@female_arms_crossed@base", anim = "base", car = 1, loop =51, e = "rece3"}},
            {label = "Ręce na biodrach [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "regal_c_3rd", car = 0, loop = 50, e = "rece4"}},
            {label = "Ręka na biodrze [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "shrug_off_a_1st", car = 0, loop = 50, e = "rece5"}},
            {label = "Obejmowanie 1 - lewo [R]", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "this_guy_b_player_a", car = 0, loop = 50, e = "obejmowanie"}},
            {label = "Obejmowanie 2 - prawo [R]", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "this_guy_b_player_b", car = 0, loop = 50, e = "obejmowanie2"}},
            {label = "Poddanie się 1 - na kolanach", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_a", car = 0, loop = 1, e = "poddanie"}},
            {label = "Poddanie się 2 [R]", type = "anim", data = {lib = "anim@move_hostages@male", anim = "male_idle", car = 0, loop = 51, e = "poddanie2"}},
            {label = "Poddanie się 3 [R]", type = "anim", data = {lib = "anim@move_hostages@female", anim = "female_idle", car = 0, loop = 51, e = "poddanie3"}},
        }
    },
	
    {
        name = 'Czynności',
        label = 'Czynności',
        items = {
        	{label = "Telefon 1 - zdjęcie", type = "scenario", data = {anim = "world_human_tourist_mobile", car = 0, loop = 0, e = "telefon"}},
            {label = "Telefon 2 - nagrywanie", type = "scenario", data = {anim = "WORLD_HUMAN_MOBILE_FILM_SHOCKING", car = 0, loop = 0, e = "telefon2"}},
         	{label = "Telefon 3 - dzwonienie [R]", type = "animprop12", data = {lib = "cellphone@", anim = "cellphone_text_to_call", car = 0, loop = 58, e = "telefon3"}},
         	{label = "Telefon 4 - pisanie [R]", type = "animprop11", data = {lib = "amb@world_human_stand_mobile@male@text@base", anim = "base", car = 0, loop = 51, e = "telefon4"}},
            {label = "Fotka - wyimaginowany aparat [P]", type = "anim", data = {lib = "anim@mp_player_intincarphotographylow@ds@", anim = "idle_a", car = 1, loop = 1, e = "fotka"}},
            {label = "Dokument z portfela", type = "animprop6", data = {lib = "random@atmrobberygen", anim = "a_atm_mugging", car = 0, loop = 0, e = "dokument"}},
			{label = "Aparat [R]", type = "animprop5", data = {lib = "amb@world_human_paparazzi@male@idle_a", anim = "idle_c", car = 1, loop = 51, e = "aparat"}},
         	{label = "Kawa [R]", type = "animprop15", data = {lib = "amb@world_human_drinking@coffee@male@idle_a", anim = "idle_c", car = 0, loop = 51, e = "kawa"}},
            {label = "Walizka 1 - skórzana [R]", type = "animprop18", data = {lib = "rcmepsilonism8", anim = "bag_handler_idle_a", car = 0, loop = 57, e = "walizka"}}, 
            {label = "Walizka 2 - metalowa [R]", type = "animprop19", data = {lib = "rcmepsilonism8", anim = "bag_handler_idle_a", car = 0, loop = 57, e = "walizka2"}}, 
            {label = "Walizka 3 - turystyczna[R]", type = "animprop20", data = {lib = "rcmepsilonism8", anim = "bag_handler_idle_a", car = 0, loop = 57, e = "walizka3"}}, 
            {label = "Walizka 4 - na kółkach [R]", type = "animprop21", data = {lib = "anim@heists@narcotics@trash", anim = "walk", car = 0, loop = 58, e = "walizka4"}},
            {label = "Tłumaczenie [R]", type = "anim", data = {lib = "misscarsteal4@actor", anim = "actor_berating_assistant", car = 1, loop = 56, e = "tlumaczenie"}},
            {label = "Zerkanie na zegarek [R]", type = "anim", data = {lib = "oddjobs@taxi@", anim = "idle_a", car = 0, loop = 56, e = "zegarek"}},
            {label = "Czyszczenie 1 - mycie ścierką", type = "scenario", data = {anim = "world_human_maid_clean", car = 0, loop = 0, e = "mycie"}},
			{label = "Czyszczenie 2 - mycie maski auta", type = "anim", data = {lib = "switch@franklin@cleaning_car", anim = "001946_01_gc_fras_v2_ig_5_base", car = 0, loop = 1, e = "mycie2"}},
			{label = "Branie prysznica 1", type = "anim", data = {lib = "mp_safehouseshower@female@", anim = "shower_idle_a", car = 0, loop = 1, e = "prysznic"}},
			{label = "Branie prysznica 2", type = "anim", data = {lib = "mp_safehouseshower@male@", anim = "male_shower_idle_a", car = 0, loop = 1, e = "prysznic2"}},
			{label = "Branie prysznica 3", type = "anim", data = {lib = "mp_safehouseshower@male@", anim = "male_shower_idle_d", car = 0, loop = 1, e = "prysznic3"}},
			{label = "Sięganie do schowka w aucie [P]", type = "animschowek", data = {lib = "rcmme_amanda1", anim = "drive_mic", car = 2, loop = 56, e = "schowek"}},
		    {label = "Włamywanie do sejfu", type = "anim", data = {lib = "mini@safe_cracking", anim = "dial_turn_anti_normal", car = 0, loop = 0, e = "sejf"}},
			{label = "Pakowanie do torby", type = "anim", data = {lib = "anim@heists@ornate_bank@grab_cash", anim = "grab", car = 0, loop = 1, e = "torba"}},
            {label = "Oddawaj pieniądze", type = "animrozmowa", data = {lib = "mini@prostitutespimp_demands_money", anim = "pimp_demands_money_pimp", car = 0, loop = 0, e = "oddawaj"}},
			{label = "Samobójstwo", type = "anim", data = {lib = "mp_suicide", anim = "pistol", car = 0, loop = 2, e = "samobojstwo"}},
        }
    },
	
    {
        name = 'Chamskie',
        label = 'Chamskie',
        items = {
			{label = "Mów do ręki [R]", type = "anim", data = {lib = "mini@prostitutestalk", anim = "street_argue_f_a", car = 0, loop = 56, e = ""}},           
		    {label = "Środkowy palec 1 [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "flip_off_a_1st", car = 0, loop = 56, e = "palec"}},
            {label = "Środkowy palec 2 - z kieszeni [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "flip_off_b_1st", car = 0, loop = 56, e = "palec2"}},
			{label = "Pokazywanie środkowych palców [R]", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter", car = 0, loop = 58, e = "palec3"}},
			{label = "Sarkastyczne klaskanie 1 [R]", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@slow_clap", anim = "slow_clap", car = 0, loop = 56, e = "klaskanie"}},
            {label = "Sarkastyczne klaskanie 2 [R]", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@slow_clap", anim = "slow_clap", car = 0, loop = 56, e = "klaskanie2"}},
            {label = "Sarkastyczne klaskanie 3 [R]", type = "anim", data = {lib = "anim@mp_player_intupperslow_clap", anim = "idle_a", car = 0, loop = 57, e = "klaskanie3"}},
			{label = "Sarkastyczne klaskanie 4", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "regal_b_3rd", car = 0, loop = 0, e = "klaskanie4"}},  
			{label = "Dokowanie", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging", car = 0, loop = 0, e = "dokowanie"}},
			{label = "Gest walenia [R][P]", type = "anim", data = {lib = "anim@mp_player_intupperdock", anim = "idle_a", car = 1, loop = 57, e = "walenie"}},
			{label = "Walenie konia 1 [P]", type = "anim", data = {lib = "anim@mp_player_intincarwanklow@ps@", anim = "idle_a", car = 1, loop = 1, e = "walenie2"}},
            {label = "Walenie konia 2 - na kogoś", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@wank", anim = "wank", car = 0, loop = 0, e = "walenie3"}},           
		    {label = "Drapanie sie po kroczu [R]", type = "anim", data = {lib = "mp_player_int_uppergrab_crotch", anim = "mp_player_int_grab_crotch", car = 0, loop = 57, e = "drapanie"}},
            {label = "Dłubanie w nosie - strzał gilem [R]", type = "anim", data = {lib = "anim@mp_player_intuppernose_pick", anim = "exit", car = 0, loop = 56, e = "dlubanie"}},
            {label = "Dłubanie w nosie 2 - oscentacyjne", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@nose_pick", anim = "nose_pick", car = 0, loop = 0, e = "dlubanie2"}},
            {label = "Ten z tyłu śmierdzi", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "taunt_c_player_b", car = 0, loop = 0, e = "smierdzi"}},
		    {label = "No dawaj! [R]", type = "anim", data = {lib = "gestures@f@standing@casual", anim = "gesture_bring_it_on", car = 0, loop = 56, e = "dawaj"}},
			{label = "Gotowość na bójkę [R][P]", type = "anim", data = {lib = "anim@mp_player_intupperknuckle_crunch", anim = "idle_a", car = 1, loop = 56, e = "bojka"}},
            {label = "Gotowość na bójkę 2 [R][P]", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@knuckle_crunch", anim = "knuckle_crunch", car = 1, loop = 56, e = "bojka2"}},           
		    {label = "Spoliczkowanie [R]", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "air_slap_a_1st", car = 0, loop = 56, e = "policzek"}},
        }
    },
	
    {
        name = 'Impreza',
        label = 'Impreza',
        items = {
            {label = "DJ", type = "anim", data = {lib = "mini@strip_club@idles@dj@idle_02", anim = "idle_02", car = 0, loop = 1, e = "dj"}},
			{label = "Oglądanie występu", type = "anim", data = {lib = "amb@world_human_strip_watch_stand@male_a@base", anim = "base", car = 0, loop = 1, e = "ogladanie"}},
            {label = "Gest 1: Ręce w górze", type = "anim", data = {lib = "mp_player_int_uppergang_sign_a", anim = "mp_player_int_gang_sign_a", car = 1, loop = 57, e = "gest"}},
            {label = "Gest 2: Znak V", type = "anim", data = {lib = "mp_player_int_upperv_sign", anim = "mp_player_int_v_sign", car = 1, loop = 57, e = "gest2"}},     
			{label = "Ukłon", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "regal_c_1st", car = 0, loop = 0, e = "uklon"}},
			{label = "Bycie pijanym", type = "anim", data = {lib = "amb@world_human_bum_standing@drunk@idle_a", anim = "idle_a", car = 0, loop = 1, e = "pijany"}},
		    {label = "Udawanie gry na gitarze", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar", car = 0, loop = 0, e = "gitara"}},
			{label = "Rock'n roll 1 [R]", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock_enter", car = 0, loop = 56, e = "rock"}},
            {label = "Rock'n roll 2 [R]", type = "anim", data = {lib = "mp_player_introck", anim = "mp_player_int_rock", car = 0, loop = 56, e = "rock2"}},           
		    {label = "Rzucanie hajsem", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@props@", anim = "make_it_rain_b_player_b", car = 0, loop = 0, e = "hajs"}},
            {label = "Śmiech", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "taunt_e_player_b", car = 0, loop = 0, e = "smiech"}},
			{label = "Pozowanie - manekin", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE", car = 0, loop = 1, e = "manekin"}},
            {label = "Wymiotowanie w aucie [P]", type = "anim", data = {lib = "oddjobs@taxi@tie", anim = "vomit_outside", car = 2, loop = 0, e = "wymioty"}},
        }
    },
	
    {
        name = 'Tańce - gotowe zestawy',
        label = 'Tańce - gotowe zestawy',
        items = {
            {label = "Taniec 1 - macarena", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_cs", anim = "dance_loop_tao", car = 0, loop = 1, e = "taniec"}},           
            {label = "Taniec 2 - wczuwanie się", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v1_female^1", car = 0, loop = 1, e = "taniec2"}},
            {label = "Taniec 3 - delikatny", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v1_female^3", car = 0, loop = 1, e = "taniec3"}},
            {label = "Taniec 4 - klubowy", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v1_female^6", car = 0, loop = 1, e = "taniec4"}},
            {label = "Taniec 5 - pływająca ręka", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@med_intensity", anim = "mi_dance_facedj_09_v1_female^1", car = 0, loop = 1, e = "taniec5"}},
            {label = "Taniec 6 - słuchawki", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_09_v1_female^1", car = 0, loop = 1, e = "taniec6"}},
            {label = "Taniec 7 - radosny", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_11_turnaround_laz", car = 0, loop = 1, e = "taniec7"}},
            {label = "Taniec 8 - klepanie", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_17_smackthat_laz", car = 0, loop = 1, e = "taniec8"}},
            {label = "Taniec 9 - chodźcie tu", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_mi_13_enticing_laz", car = 0, loop = 1, e = "taniec9"}},
            {label = "Taniec 10 - stepowanie", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag", car = 0, loop = 1, e = "taniec10"}},
        }
    },

    {
        name = 'Tańce - własne',
        label = 'Tańce - własne',
        items = {
			{label = "Taniec A - baza", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center", car = 0, loop = 1, e = ""}},
			{label = "Taniec A - ręce w dół", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec A - ręce w górę", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec A - ręce w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_left", car = 0, loop = 1, e = ""}},
			{label = "Taniec A - ręce w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_right", car = 0, loop = 1, e = ""}},			
			{label = "Taniec A - lewa w górę", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_left_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec A - prawa w górę", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_right_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec B - baza", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_center", car = 0, loop = 1, e = ""}},
			{label = "Taniec B - ręce w górę lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_left_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec B - ręce w górę w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_right_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec B - ręce w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_left", car = 0, loop = 1, e = ""}},
			{label = "Taniec B - ręce w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "low_right", car = 0, loop = 1, e = ""}},
			{label = "Taniec C - baza", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_center", car = 0, loop = 1, e = ""}},
			{label = "Taniec C - ręce w górę w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_left_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec C - ręce w górę w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_right_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec C - ręce w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_left", car = 0, loop = 1, e = ""}},
			{label = "Taniec C - ręce w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "med_right", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - baza", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "high_center_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - ręce w dół klaskanie", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - ręce w górę", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - ręce w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_left_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - ręce w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_right_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - lewa w górę", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_left_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec D - prawa w górę", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_right_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec E - baza", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "low_center", car = 0, loop = 1, e = ""}},
			{label = "Taniec E - baza smutas", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "low_center_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec E - lewy palec", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "low_left", car = 0, loop = 1, e = ""}},
			{label = "Taniec E - prawy palec", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "low_right", car = 0, loop = 1, e = ""}},
			{label = "Taniec F - baza", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_center", car = 0, loop = 1, e = ""}},
			{label = "Taniec F - baza pochylona", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_center_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec F - ręce w górę w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_left_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec F - ręce w górę w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_right_up", car = 0, loop = 1, e = ""}},
			{label = "Taniec F - ręce w dół w lewo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_left_down", car = 0, loop = 1, e = ""}},
			{label = "Taniec F - ręce w dół w prawo", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "med_right_down", car = 0, loop = 1, e = ""}},
        }
    },

    {
        name = 'Bezczynność',
        label = 'Bezczynność',
        items = {
            {label = "Niecierpliwosc", type = "anim", data = {lib = "oddjobs@taxi@", anim = "base", car = 0, loop = 1, e = "niecierpliwosc"}},
            {label = "Rozmowa 1 - założone ręce", type = "anim", data = {lib = "amb@world_human_hang_out_street@male_c@base", anim = "base", car = 0, loop = 1, e = "rozmowa"}},
            {label = "Rozmowa 2 - założone ręce", type = "anim", data = {lib = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", anim = "idle_a", car = 0, loop = 0, e = "rozmowa2"}},
            {label = "Rozmowa 3 - trzymana lewa ręka", type = "anim", data = {lib = "amb@world_human_hang_out_street@female_hold_arm@idle_a", anim = "idle_b", car = 0, loop = 0, e = "rozmowa3"}},
        }
    },

    {
        name = 'Sport',
        label = 'Sport',
        items = {
            {label = "Jogging [R]", type = "anim", data = {lib = "move_m@jogger", anim = "run", car = 0, loop = 33, e = "jogging"}},
            {label = "Trucht [R]", type = "anim", data = {lib = "move_m@jog@", anim = "run", car = 0, loop = 33, e = "trucht"}},
            {label = "Powerwalk [R]", type = "anim", data = {lib = "amb@world_human_power_walker@female@base", anim = "base", car = 0, loop = 33, e = "powerwalk"}},
            {label = "Napinanie mięśni", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base", car = 0, loop = 1, e = "napinanie"}},
            {label = "Pompki", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base", car = 0, loop = 1, e = "pompki"}},
            {label = "Brzuszki", type = "animangle", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base", car = 0, loop = 1, e = "brzuszki"}},
            {label = "Salto w tył", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "flip_a_player_a", car = 0, loop = 0, e = "salto"}},
            {label = "Capoeira", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "cap_a_player_a", car = 0, loop = 0, e = "capoeira"}},
            {label = "Yoga 1 - przygotowanie", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base", car = 0, loop = 1, e = "yoga"}},
            {label = "Yoga 2 - rozciąganie się", type = "anim", data = {lib = "amb@world_human_yoga@female@base", anim = "base_b", car = 0, loop = 1, e = "yoga2"}},
            {label = "Yoga 3 - stanie na rękach", type = "anim", data = {lib = "amb@world_human_yoga@female@base", anim = "base_c", car = 0, loop = 1, e = "yoga3"}},
            {label = "Baseball 1 - kij", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@no_props@", anim = "slugger_a_player_a", car = 0, loop = 0, e = "baseball"}},
            {label = "Baseball 2 - rzut piłką", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "baseball_a_player_a", car = 0, loop = 0, e = "baseball2"}},
            {label = "Baseball 3 - rzut piłką", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "baseball_a_player_b", car = 0, loop = 0, e = "baseball3"}},
        }
    },

    {
        name = 'Romanse',
        label = 'Romanse',
        items = {
            {label = "Przytul 1", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a", car = 0, loop = 0, e = "przytul"}},
            {label = "Przytul 2", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_b", car = 0, loop = 0, e = "przytul2"}},        	
            {label = "Całus 1 [R][P]", type = "anim", data = {lib = "anim@mp_player_intselfieblow_kiss", anim = "exit", car = 1, loop = 56, e = "calus"}},
            {label = "Całus 2", type = "anim", data = {lib = "mini@hookers_sp", anim = "idle_a", car = 0, loop = 0, e = "calus2"}},
            {label = "Całus 3 [R]", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@blow_kiss", anim = "blow_kiss", car = 0, loop = 56, e = "calus3"}},
            {label = "Uroczo [R][P]", type = "anim", data = {lib = "mini@hookers_spcokehead", anim = "idle_reject_loop_a", car = 1, loop = 58, e = "uroczo"}},
			{label = "Zawstydzenie", type = "anim", data = {lib = "anim@arena@celeb@podium@no_prop@", anim = "regal_a_3rd", car = 0, loop = 0, e = ""}},          
		    {label = "Uwodzenie", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02", car = 0, loop = 1, e = "uwodzenie"}},
            {label = "Eksponowanie wdzięków - przód", type = "anim", data = {lib = "mini@hookers_sp", anim = "ilde_b", car = 0, loop = 1, e = "wdzieki"}},
            {label = "Eksponowanie wdzięków - tył", type = "anim", data = {lib = "mini@hookers_sp", anim = "ilde_c", car = 0, loop = 1, e = "wdzieki2"}},
            {label = "Zmysłowy taniec", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_li_15_sexygrind_laz", car = 0, loop = 1, e = "zmyslowy"}},
            {label = "Taniec erotyczny 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f", car = 0, loop = 1, e = "erotyczny"}},
            {label = "Taniec erotyczny 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2", car = 0, loop = 1, e = "erotyczny2"}},
            {label = "Taniec erotyczny 3", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3", car = 0, loop = 1, e = "erotyczny3"}},
        }
    },

    {
        name = 'Praca',
        label = 'Praca',
        items = {
            {label = "Karton [R]", type = "animprop17", data = {lib = "anim@heists@box_carry@", anim = "idle", car = 0, loop = 57, e = "karton"}},
			{label = "Wiertarka [R]", type = "animprop22", data = {lib = "anim@heists@fleeca_bank@drilling", anim = "drill_straight_start", car = 0, loop = 57, e = "wiertarka"}},
            {label = "Skrzynka 1 - z narzędziami [R]", type = "animprop23", data = {lib = "rcmepsilonism8", anim = "bag_handler_idle_a", car = 0, loop = 57, e = "skrzynka"}},
            {label = "Skrzynka 2 - z narzędziami [R]", type = "animprop24", data = {lib = "rcmepsilonism8", anim = "bag_handler_idle_a", car = 0, loop = 57, e = "skrzynka2"}},    
            {label = "Mechanik 1 - maska", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped", car = 0, loop = 1, e = "mechanik"}},
            {label = "Mechanik 2 - maska", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_player", car = 0, loop = 1, e = "mechanik2"}},
            {label = "Mechanik 3 - pod autem", type = "animangle", data = {lib = "amb@world_human_vehicle_mechanic@male@base", anim = "base", car = 0, loop = 1, e = "mechanik3"}},
            {label = "Mechanik 4 - wyjście spod auta", type = "anim", data = {lib = "amb@world_human_vehicle_mechanic@male@exit", anim = "exit", car = 0, loop = 0, e = "mechanik4"}},
            {label = "Taxi 1 - rozmowa z klientem [P]", type = "anim", data = {lib = "oddjobs@taxi@driver", anim = "leanover_idle", car = 2, loop = 1, e = "taxi"}},
            {label = "Taxi 2 - podawanie rachunku [P]", type = "anim", data = {lib = "oddjobs@taxi@cyi", anim = "std_hand_off_ps_passenger", car = 2, loop = 0, e = "taxi2"}},
            {label = "Łowienie wędką", type = "scenario", data = {anim = "WORLD_HUMAN_STAND_FISHING", car = 0, loop = 1, e = "wedka"}},
		    {label = "Uderzanie młotkiem", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING", car = 0, loop = 0, e = "mlotek"}},
			{label = "Spawanie", type = "scenario", data = {anim = "WORLD_HUMAN_WELDING", car = 0, loop = 1, e = "spawanie"}},
            {label = "Pisanie na komputerze", type = "anim", data = {lib = "anim@heists@prison_heistig1_p1_guard_checks_bus", anim = "loop", car = 0, loop = 1, e = "komputer"}},
            {label = "Barman - polewanie kolejki", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b", car = 0, loop = 0, e = "barman"}},
--          {label = "Trzymanie tekturowej kartki", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY", car = 0, loop = 0, e = ""}},
--          {label = "Używanie lornetki", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS", car = 0, loop = 0, e = ""}},
            {label = "Ładowanie towaru", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper", car = 0, loop = 0, e = "towar"}},
            {label = "Kopanie w ziemi 1", type = "animprop3", data = {lib = "random@burial", car = 0, e = "kopanie"}},
			{label = "Kopanie w ziemi 2 - klękanie", type = "scenario", data = {anim = "world_human_gardener_plant", car = 0, loop = 0, e = "kopanie2"}},
			{label = "Patrzenie w notatki", type = "animprop8", data = {lib = "amb@world_human_clipboard@male@idle_a", anim = "idle_c", car = 0, loop = 51, e = "notatki"}},
        }
    },

    {
        name = 'EMS / LSPD',
        label = 'EMS / LSPD',
        items = {
            {label = "Sprawdzanie stanu 1 - klękanie", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL", car = 0, loop = 0, e = "stan"}},
            {label = "Sprawdzanie stanu 2 - uciskanie", type = "anim", data = {lib = "anim@heists@narcotics@funding@gang_idle", anim = "gang_chatting_idle01", car = 0, loop = 1, e = "stan2"}},	
            {label = "Łykanie tabletki [R]", type = "animtabletka", data = {lib = "mp_suicide", anim = "pill", car = 1, loop = 56, e = "tabletka"}},			
		    {label = "Ból w klatce piersiowej", type = "animangle", data = {lib = "anim@heists@prison_heistig_5_p1_rashkovsky_idle", anim = "idle", car = 0, loop = 1, e = "klatka"}},
            {label = "Ból nogi", type = "anim", data = {lib = "missfbi5ig_0", anim = "lyinginpain_loop_steve", car = 0, loop = 1, e = "noga"}},
            {label = "Drgawki", type = "anim", data = {lib = "missheistfbi3b_ig8_2", anim = "cpr_loop_victim", car = 0, loop = 1, e = "dragwki"}},
         	{label = "Omdlenie 1 - prawy bok", type = "anim", data = {lib = "dam_ko@shot", anim = "ko_shot_head", car = 0, loop = 2, e = "omdlenie"}},
            {label = "Omdlenie 2 - na plecy", type = "anim", data = {lib = "anim@gangops@hostage@", anim = "perp_success", car = 0, loop = 2, e = "omdlenie2"}},
            {label = "Omdlenie 3 - leżąc", type = "anim", data = {lib = "mini@cpr@char_b@cpr_def", anim = "cpr_intro", car = 0, loop = 2, e = "omdlenie3"}},
			{label = "Ocknięcie 1 - ponowne omdlenie", type = "anim", data = {lib = "missfam5_blackout", anim = "pass_out", car = 0, loop = 2, e = "ockniecie"}},
			{label = "Ocknięcie 2 - wymiotowanie", type = "animockniecie", data = {lib = "missfam5_blackout", anim = "vomit", car = 0, loop = 0, e = "ockniecie2"}},
			{label = "Ocknięcie 3 - szybko", type = "anim", data = {lib = "safe@trevor@ig_8", anim = "ig_8_wake_up_front_player", car = 0, loop = 0, e = "ockniecie3"}},
			{label = "Ocknięcie 4 - powoli", type = "anim", data = {lib = "safe@trevor@ig_8", anim = "ig_8_wake_up_right_player", car = 0, loop = 0, e = "ockniecie4"}},
            {label = "Brak przytomności 1", type = "anim", data = {lib = "mini@cpr@char_b@cpr_def", anim = "cpr_pumpchest_idle", car = 0, loop = 1, e = "nieprzytomnosc"}},
			{label = "Brak przytomności 2", type = "anim", data = {lib = "missprologueig_6", anim = "lying_dead_brad", car = 0, loop = 1, e = "nieprzytomnosc2"}},
            {label = "Brak przytomności 3", type = "anim", data = {lib = "missprologueig_6", anim = "lying_dead_player0", car = 0, loop = 1, e = "nieprzytomnosc3"}},
			{label = "Brak przytomności 4 - na brzuchu", type = "animangle2", data = {lib = "missarmenian2", anim = "drunk_loop", car = 0, loop = 1, e = "nieprzytomnosc4"}},
            {label = "RKO 1 - uciskanie", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_pumpchest", car = 0, loop = 1, e = "rko"}},
            {label = "RKO 2 - wdechy", type = "anim", data = {lib = "mini@cpr@char_a@cpr_str", anim = "cpr_kol", car = 0, loop = 1, e = "rko2"}},
			{label = "Operacja / trumna", type = "anim", data = {lib = "anim@gangops@morgue@table@", anim = "ko_back", car = 0, loop = 1, e = "operacja"}},
            {label = "Wzywanie SOS - rękoma [R]", type = "anim", data = {lib = "random@gang_intimidation@", anim = "001445_01_gangintimidation_1_female_wave_loop", car = 0, loop = 51, e = "sos"}},
            {label = "Sprawdzanie dowodów", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f", car = 0, loop = 0, e = "dowody"}},
			{label = "Kierowanie ruchem", type = "animprop", data = {lib = "amb@world_human_car_park_attendant@male@base", anim = "base", car = 0, loop = 1, e = "kierowanie"}},
			{label = "Notes", type = "animprop2", data = {lib = "amb@medic@standing@timeofdeath@base", anim = "base", car = 1, loop = 51, e = "notes"}},
        }
    },

    {
      name  = 'Style chodzenia',
      label = 'Style chodzenia',
      items = {
          {label = "Normalny [K]", type = "walkstyle", data = {lib = "move_f@generic", anim = "move_f@generic", e = ""}},
          {label = "Normalny [M]", type = "walkstyle", data = {lib = "move_m@generic", anim = "move_m@generic", e = ""}},
          {label = "Pewniak [K]", type = "walkstyle", data = {lib = "move_f@heels@d", anim = "move_f@heels@d", e = ""}},
          {label = "Pewniak [M]", type = "walkstyle", data = {lib = "move_m@confident", anim = "move_m@confident", e = ""}},
          {label = "Gruby [K]", type = "walkstyle", data = {lib = "move_f@fat@a", anim = "move_f@fat@a", e = ""}},
          {label = "Gruby [M]", type = "walkstyle", data = {lib = "move_m@fat@a", anim = "move_m@fat@a", e = ""}},
          {label = "Poszkodowany [K]", type = "walkstyle", data = {lib = "move_f@injured", anim = "move_f@injured", e = ""}},
          {label = "Poszkodowany [M]", type = "walkstyle", data = {lib = "move_m@injured", anim = "move_m@injured", e = ""}},
          {label = "Zuchwały [K]", type = "walkstyle", data = {lib = "move_f@sassy", anim = "move_f@sassy", e = ""}},
          {label = "Zuchwały [M]", type = "walkstyle", data = {lib = "move_m@sassy", anim = "move_m@sassy", e = ""}},
          {label = "Smutny", type = "walkstyle", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a", e = ""}},
          {label = "Biznes", type = "walkstyle", data = {lib = "move_m@business@a", anim = "move_m@business@a", e = ""}},
          {label = "Odważny", type = "walkstyle", data = {lib = "move_m@brave@a", anim = "move_m@brave@a", e = ""}},
          {label = "Luzak", type = "walkstyle", data = {lib = "move_m@casual@e", anim = "move_m@casual@e", e = ""}},
          {label = "Hipster", type = "walkstyle", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a", e = ""}},
          {label = "Smutny", type = "walkstyle", data = {lib = "move_m@sad@a", anim = "move_m@sad@a", e = ""}},
          {label = "Siłacz", type = "walkstyle", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a", e = ""}},
          {label = "Gangster 1", type = "walkstyle", data = {lib = "move_m@gangster@generic", anim = "move_m@gangster@generic", e = ""}},
          {label = "Gangster 2", type = "walkstyle", data = {lib = "move_m@money", anim = "move_m@money", e = ""}},
          {label = "Wspinaczka", type = "walkstyle", data = {lib = "move_m@hiking", anim = "move_m@hiking", e = ""}},
          {label = "Bezdomny", type = "walkstyle", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a", e = ""}},
          {label = "Podpity", type = "walkstyle", data = {lib = "move_m@buzzed", anim = "move_m@buzzed", e = ""}},
          {label = "Średnio Pijany", type = "walkstyle", data = {lib = "move_m@drunk@moderatedrunk", anim = "move_m@drunk@moderatedrunk", e = ""}},
          {label = "Bardzo Pijany", type = "walkstyle", data = {lib = "move_m@drunk@verydrunk", anim = "move_m@drunk@verydrunk", e = ""}},
          {label = "W pośpiechu 1", type = "walkstyle", data = {lib = "move_m@hurry_butch@b", anim = "move_m@hurry_butch@b", e = ""}},
          {label = "W pośpiechu 2", type = "walkstyle", data = {lib = "move_m@hurry@b", anim = "move_m@hurry@b", e = ""}},
          {label = "Szybki", type = "walkstyle", data = {lib = "move_m@quick", anim = "move_m@quick", e = ""}},
      }
  },

 --[[{
         name = 'ANIM',
        label = 'DO SKRYPTÓW',
        items = {
            {label = "Fajka", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING", car = 0, loop = 1, e = ""}},
            {label = "Narko wciaganie", type = "anim", data = {lib = "safe@trevor@ig_8", anim = "ig_8_huff_gas_player", car = 0, loop = 2, e = ""}},
            {label = "jedzenie pączka", type = "anim", data = {lib = "amb@code_human_wander_eating_donut@male@idle_a", anim = "idle_a", car = 0, loop = 56, e = ""}},
            {label = "noszenie starego na plecach", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "piggyback_b_player_a", car = 0, loop = 50, e = ""}},
            {label = "stary na plecach", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "piggyback_b_player_b", car = 0, loop = 0, e = ""}},
            {label = "noszenie starego na plecach2", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "piggyback_c_player_a", car = 0, loop = 50, e = ""}},
            {label = "stary na plecach2", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "piggyback_c_player_b", car = 0, loop = 0, e = ""}},
            {label = "prop szampana", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@props@", anim = "chug_beer_a_player_a", car = 0, loop = 0, e = ""}},
            {label = "prop szampana 2", type = "anim", data = {lib = "anim@arena@celeb@flat@solo@props@", anim = "chug_beer_b_player_a", car = 0, loop = 0, e = ""}},
            {label = "picie szampana", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@props@", anim = "cham_a_player_a", car = 0, loop = 0, e = ""}},
            {label = "Graba 2", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "daps_b_player_a", car = 0, loop = 0, e = ""}},
            {label = "Graba 3", type = "anim", data = {lib = "anim@arena@celeb@flat@paired@no_props@", anim = "daps_b_player_b", car = 0, loop = 0, e = ""}},
			{label = "Hostage3", type = "anim", data = {lib = "anim@gangops@hostage@", anim = "perp_idle", car = 0, loop = 0, e = ""}},
			{label = "Hostage4", type = "anim", data = {lib = "anim@gangops@hostage@", anim = "victim_idle", car = 0, loop = 0, e = ""}},
			{label = "Graba1", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a", car = 0, loop = 0, e = ""}},
			{label = "Graba2", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_b", car = 0, loop = 0, e = ""}},
			{label = "Handshake1", type = "anim", data = {lib = "mp_common", anim = "givetake1_a", car = 0, loop = 0, e = ""}},
			{label = "Handshake2", type = "anim", data = {lib = "mp_common", anim = "givetake1_b", car = 0, loop = 0, e = ""}},
			{label = "Handshake3", type = "anim", data = {lib = "mp_common", anim = "givetake2_a", car = 0, loop = 0, e = ""}},
			{label = "Handshake4", type = "anim", data = {lib = "mp_common", anim = "givetake2_b", car = 0, loop = 0, e = ""}},
			{label = "BJ - ona", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_hooker", car = 0, loop = 1, e = ""}},
            {label = "BJ - on", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_punter", car = 0, loop = 1, e = ""}},
            {label = "BJ w aucie - kierowca", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_bj_loop_player", car = 0, loop = 1, e = ""}},
            {label = "BJ w aucie - pasażer", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_bj_loop_female", car = 0, loop = 1, e = ""}},
            {label = "Seks w aucie - pasażer", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_female", car = 0, loop = 1, e = ""}},
            {label = "Seks w aucie - kierowca", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_player", car = 0, loop = 1, e = ""}},
			{label = "Pod ścianą - ona", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "shagloop_hooker", car = 0, loop = 1, e = ""}},
            {label = "Pod ścianą - on", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "shagloop_pimp", car = 0, loop = 1, e = ""}},
            {label = "Od tyłu - on", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_a", car = 0, loop = 1, e = ""}},
            {label = "Od tyłu - ona", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_poppy", car = 0, loop = 1, e = ""}},
            {label = "Okulary - zakładanie", type = "anim", data = {lib = "clothingspecs", anim = "try_glasses_negative_b", car = 0, loop = 0, e = ""}},
            {label = "Okulary - zdejmowanie", type = "anim", data = {lib = "clothingspecs", anim = "take_off", car = 0, loop = 0, e = ""}},
            {label = "Szyja", type = "anim", data = {lib = "clothingtie", anim = "try_tie_positive_a", car = 0, loop = 0, e = ""}},
            {label = "Zegarek", type = "anim", data = {lib = "anim@random@shop_clothes@watches", anim = "idle_d", car = 0, loop = 0, e = ""}},
            {label = "Koszulka", type = "anim", data = {lib = "clothingshirt", anim = "try_shirt_positive_d", car = 0, loop = 0, e = ""}},
            {label = "Spodnie", type = "anim", data = {lib = "clothingtrousers", anim = "try_trousers_neutral_c", car = 0, loop = 0, e = ""}},
            {label = "Buty", type = "anim", data = {lib = "clothingshoes", anim = "try_shoes_positive_d", car = 0, loop = 0, e = ""}},
            {label = "Maska - zdejmowanie", type = "anim", data = {lib = "missfbi4", anim = "takeoff_mask", car = 0, loop = 0, e = ""}},
            {label = "Maska - zakładanie", type = "anim", data = {lib = "missheistdockssetup1hardhat@", anim = "put_on_hat", car = 0, loop = 0, e = ""}},
          	{label = "Kolczyki", type = "anim", data = {lib = "anim@amb@nightclub@djs@switch@tale_djset_switchover@", anim = "tale_start_mm", car = 0, loop = 51, e = ""}},
			{label = "Bransoletka", type = "anim", data = {lib = "clothingshirt", anim = "try_shirt_negative_c", car = 0, loop = 0, e = ""}},
            {label = "Ped w bagazniku", type = "anim", data = {lib = "mp_common_miss", anim = "dead_ped_idle", car = 1, loop = 0, e = ""}},
            {label = "Sypanie z worka", type = "anim", data = {lib = "weapon@w_sp_jerrycan", anim = "fire", car = 0, loop = 1, e = ""}},
            {label = "Dojenie krowy", type = "anim", data = {lib = "weapon@w_sp_jerrycan", anim = "discard_crouch", car = 0, loop = 1, e = ""}},
			{label = "Kupowanie w sklepie", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beer_shopkeeper", car = 0, loop = 0, e = ""}},
            {label = "Podnoszenie itemku", type = "anim", data = {lib = "random@atmrobberygen", anim = "pickup_low", car = 0, loop = 0, e = ""}},
			{label = "Przeszukanie1", type = "anim", data = {lib = "anim@gangops@facility@servers@bodysearch@", anim = "player_search", car = 0, loop = 56, e = ""}},
			{label = "Przeszukanie2", type = "anim", data = {lib = "anim@gangops@morgue@table@", anim = "player_search", car = 0, loop = 56, e = ""}},
			{label = "Blacha", type = "animprop4", data = {lib = "random@atm_robbery@return_wallet_male", anim = "return_wallet_positive_a_player", car = 1, loop = 56, e = ""}},
          	{label = "Noszenie", type = "anim", data = {lib = "rcmpaparazzo_4", anim = "gesture_to_cam_camman", car = 0, loop = 51, e = ""}},
            {label = "Noszony", type = "anim", data = {lib = "amb@world_human_bum_slumped@male@laying_on_left_side@base", anim = "base", car = 0, loop = 1, e = ""}},
			{label = "Kasa z portfela 1", type = "animprop7", data = {lib = "random@atmrobberygen", anim = "a_atm_mugging", car = 0, loop = 0, e = ""}},
			{label = "Kasa z portfela 2 - więcej", type = "animprop9", data = {lib = "random@atmrobberygen", anim = "a_atm_mugging", car = 0, loop = 0, e = ""}},
        }
    },]]
}
